# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Run `repogen`

on:
  workflow_dispatch:
    inputs:
      repository_name:
        type: text
        required: true
        description: Name of the repository to act on, e.g. `sample-repo`
      repogen_subcommand:
        type: choice
        options:
          - create-repo
          - destroy-repo
        required: true
        description: Create a repo or update an existing one; or delete a repo.
        default: create-repo

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    - run: pip install -e .
    - run: |
        echo "Running repogen with the following inputs"
        echo "    repogen_subcommand: ${{ inputs.repogen_subcommand }}"
        echo "       repository_name: ${{ inputs.repository_name }}"
        repogen ${{ inputs.repogen_subcommand }} --repo-name "${{ repository_name }}"
